### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Nono9k** [carlossless/sh68f90a-experiments#13]
Hey! Just wondering if they'd ever be a discord for this project, i feel it could be beneficial, it could make the community for smk bigger, and people don't have to make more github issues asking for help lol. I understand if you'd like to keep it smaller and having a discord might put a bit of pressure on you. I could help set it up. If you don't want to make a discord that's completely fine. Just a suggestion! 
Thanks!

**Comment by carlossless** [comment]
I was actually thinking about this recently!

I think it's a bit too early to start a discord (or any sort of group chat - matrix, etc.) for the same reasons you already mentioned. I'm not ready to support a community and would like first to finish:
* multiple keyboard/layout build setup
* work out of some of the known bugs
* add documentation for building and contributing

Once those are done, I'd be happy to set things up and participate, so stay tuned, I don't think it's too going to take very long now :)

**Comment by carlossless** [comment]
I revised the build setup and added minimal building documentation.
At this point, I figure, having a bit of community around the project could be helpful :).

Join up here: https://discord.com/invite/SZFBDBuxrK

**Comment by NotJustAnna** [comment]
Is the Discord still around?

**Comment by carlossless** [comment]
Yes! I updated the invite link in my previous post. Use it to join up.
