### ISSUE TITLE
How to build this for redragon k631

### ISSUE THREAD

**Issue by A-Rint-A** [carlossless/sh68f90a-experiments#8]
unfortunately you left no guide or hints, I have several copies of this keyboard and I have a place to dump the original flash memory if something happens, I will be glad to be a guinea pig.

**Comment by carlossless** [comment]
Hey, this firmware is still highly experimental, full of bugs, and lacks a bunch of features. At this point, I don't recommend using it unless you are capable of working with it as is (porting it to your own device).

See my notes on https://github.com/carlossless/smk/issues/6#issuecomment-1987316608 and check out @timaxur's attempt here https://github.com/carlossless/smk/issues/3#issuecomment-1878325756

**Comment by A-Rint-A** [comment]
I'm not afraid of any problems, I have the opportunity to suddenly install an original dump, I've just never dealt with compiling firmware

**Comment by A-Rint-A** [comment]
For one thing, I will be happy to help with catching these same errors on this keyboard, which I think is useful for all of us

**Comment by A-Rint-A** [comment]
What files need to be modified besides layout.c and makefile?

**Comment by A-Rint-A** [comment]
In general, I got to build it although not without problems, but it works and did not even break my bootloader, which is already happy
